# Generated by Django 4.2.3 on 2023-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='url_imagem',
            field=models.URLField(default='', max_length=400),
        ),
    ]
